[project]
name = "windygraph-a-graph-based-recommender-for-restaurants-in-chicago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
